import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            background: "lightblue",
            marginTop: "0px",

            textAlign: "center",
            position: "fixed",

            padding: "50px",

            width: "100%",
          }}
        >
          <div>
            <h2>Snake Game</h2>
          </div>
          <Link href="/child">Child</Link> <br />
          <Link href="/settings">Settings</Link>
        </header>
        {children}
        <footer
          style={{
            background: "cyan",
            position: "fixed",
            bottom: "0",
            width: "100%",
            textAlign: "center",
            padding: "50px",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
