import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header style={{background: "lightblue",
            padding: "100px"}}>
                    <Link href="/child">Child</Link> <br />
                    <Link href="/settings">Settings</Link>
                </header>
                {children}
                <footer style={{background: "cyan",
            padding: "50px"}}>
                    Footer
                </footer>

            </body>
        </html>
    );
}
